# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../../RIOT

# name of the application
APPLICATION = crypto-ewsn2020_cryptoauth_ecdh

USEPKG += cryptoauthlib
USEMODULE += hashes
include $(RIOTBASE)/Makefile.include
